config/routes.rb
MovieSite::Application.routes.draw do
  resources :user_sessions
  
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => 'user_sessions#create', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'register' => 'users#new'

  resources :users

  resources :movies do
    resources :comments
  end
  
  root :to => "movies#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, User
      
      # if user logged in ...
      if user.id?
        can :create, Movie
        can :create, Comment
        
        can :update, Movie
        can :update, Comment, :user_id => user.id
        
        can :destroy, Comment, :user_id => user.id
      end
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :comments
  
  GENRES = ['Horror', 'Sci-Fi', 'Action', 'Fantasy']
  
  validates :title, :presence => true
  validates :director, :presence => true
  validates :starring, :presence => true
  validates :genre, :inclusion => { :in => GENRES, :message => 'must be selected' }
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  
  has_many :comments
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # specify configuration here, such as:
  # logout_on_timeout true
  # ...many more options in the documentation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper :all
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = "Access denied."
    redirect_to root_url
  end
  
  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end
    
    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.record
    end
    
    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        #redirect_to account_url
        redirect_to root_url
        return false
      end
    end
    
    def store_location
      session[:return_to] = request.request_uri
    end
    
    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  
  before_filter :require_user, :only => [:create, :edit, :update, :destroy]
  before_filter :load_movie
  
  def new
  end
  
  def edit
  end

  def create
    @comment.movie = @movie
    @comment.user = current_user

    if @comment.save
      redirect_to(@movie, :notice => 'Comment was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update_attributes(params[:comment])
      redirect_to(@movie, :notice => 'Comment was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @comment.destroy

    redirect_to(@movie)
  end
  
  def load_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  load_and_authorize_resource
  before_filter :require_user, :only => [:new, :edit, :create, :update, :destroy]
  # GET /movies
  def index
  end

  # GET /movies/1
  def show
    @comment = @movie.comments.new
  end

  # GET /movies/new
  def new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  def create
    if @movie.save
      redirect_to(@movie, :notice => 'Movie was successfully added.')
    else
      render :action => "new"
    end
  end

  # PUT /movies/1
  def update
    if @movie.update_attributes(params[:movie])
      redirect_to(@movie, :notice => 'Movie was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /movies/1
  def destroy
    @movie.destroy

    flash[:alert] = 'Movie was successfully deleted.'
    redirect_to(movies_url)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @usersession = UserSession.new
  end
  
  def create
    @usersession = UserSession.new(params[:user_session])
    
    if @usersession.save
      #redirect_to(root_url, :notice => 'Successfully logged in.')
      flash[:notice] = 'Successfully logged in.'
      redirect_back_or_default root_url
    else
      render :action => "new"
    end
  end
    
  def destroy
    current_user_session.destroy
    
    redirect_to(root_url, :notice => "Successfully logged out.")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, :only => [:edit,:update,:destroy]
  before_filter :require_no_user, :only => [:new,:create]
  load_and_authorize_resource
  def index
  end
  
  def show
  end
  
  def new
  end

  def edit
  end

  def create
    if @user.save
      redirect_to(@user, :notice => 'User was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to(@user, :notice => 'User was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @user.destroy

    redirect_to(users_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def relative_date(date)
    if 1.day.ago < date
      time_ago_in_words(date) + " ago"
    elsif 2.days.ago < date
      date.getlocal.strftime("Yesterday at %I:%M %p")
    elsif 4.days.ago < date
      date.getlocal.strftime("%A at %I:%M %p")
    else
      date.getlocal.strftime("%B %d, %Y at %I:%M %p")
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<% form_for [@movie, @comment] do |f| %>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Post Comment" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= render 'comments/form' %>

app/views/comments/new.html.erb
<h3>Add comment</h3>

<%= render 'comments/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieSite</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<h1>Movie Website</h1>

<%= link_to "Home", root_url %> |
<% if current_user %>
  <%= link_to "Logout", logout_path %>
<% else %>
  <%= link_to "Register", register_path %> | 
  <%= link_to "Login", login_path %>
<% end %>

<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :director %><br />
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :starring %><br />
    <%= f.text_field :starring %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.collection_select(:genre, Movie::GENRES, :to_s, :to_s, :prompt => true) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h2>Editing movie</h2>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h2>Listing movies</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Director</th>
    <th>Starring</th>
    <th>Genre</th>
    <th></th>
    <th></th>
  </tr>
  <% @movies.each do |movie| %>
  <tr>
    <td><%= link_to movie.title, movie %></td>
    <td><%= movie.director %></td>
    <td><%= movie.starring %></td>
    <td><%= movie.genre %></td>
    <% if can? :edit, Movie %>
      <td><%= link_to "Edit", edit_movie_path(movie)%></td>
    <% end %>
    <% if can? :destroy, Movie %>
      <td><%= link_to 'Destroy', movie, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
  <% end %>
</table>

<br />
<% if can? :create, Movie %>
  <%= link_to 'New Movie', new_movie_path %>
<% end %>

app/views/movies/new.html.erb
<h2>Add movie</h2>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<h2>Showing Movie</h2>
<p>
  <b>Title:</b>
  <%= @movie.title %>
</p>

<p>
  <b>Directors:</b>
  <%= @movie.director %>
</p>

<p>
  <b>Starring:</b>
  <%= @movie.starring %>
</p>

<p>
  <b>Genre:</b>
  <%= @movie.genre %>
</p>

<% unless @movie.comments.empty? %>
  <h3><%= pluralize(@movie.comments.size, 'comment') %></h3>

  <div id="comments">
  <% @movie.comments.each do |comment| %>
    <div class="comment">
      <strong><%= comment.user.username %></strong>
      <em>on <%= relative_date(comment.created_at) %></em>
      <p><%= comment.content %></p>
      <p>
        <% if can? :edit, comment %>
          <%= link_to "Edit", edit_movie_comment_path(@movie, comment) %>
        <% end %>
        <% if can? :destroy, comment %>
         |  <%= link_to 'Delete', [ @movie, comment ], :confirm => 'Are you sure?', :method => :delete %>
        <% end %>
      </p>
      <hr>
    </div>
  <% end %>
  </div>
<% end %>

<% if can? :create, Comment %>
<%= render :file => 'comments/new' %>
<% end %>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/user_sessions/new.html.erb
<h2>Login</h2>

<%= form_for @usersession, :as => :user_session, :url => login_path do |f| %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>Editing user</h2>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>Listing users</h2>

<table>
  <tr>
    <th>Username</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.username, user %></td>
    <% if can? :edit, user %>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <%end%>
    <% if can? :destroy, user %>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
    <%end%>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h2>Register</h2>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2>Showing User</h2>
<p>
  <b>Username:</b>
  <%= @user.username %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>